# Name for the workflow
name: Build and Release

# This section defines the trigger
on:
  release:
    # This workflow runs only when a new release is "created"
    types: [created]

# A single job named "build-release"
jobs:
  build-release:
    # It must run on a Windows environment
    runs-on: windows-latest

    # --- ADD THIS BLOCK ---
    # Grant the job permission to write to the repository's contents,
    # which is required for uploading release assets.
    permissions:
      contents: write
    # ----------------------

    # The steps for the job
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Compile the C file into pbw.exe
      - name: Compile C file
        run: gcc pbw.c -o pbw.exe

      # Step 3: Upload the compiled .exe to the GitHub Release
      - name: Upload to Release
        run: gh release upload "${{ github.event.release.tag_name }}" pbw.exe
        env:
          # This token now has the 'contents: write' permission
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
