# Name for the workflow
name: Build and Release

# This section defines the trigger
on:
  release:
    # This workflow runs only when a new release is "created" (not edited or deleted)
    types: [created]

# A single job named "build-release"
jobs:
  build-release:
    # It must run on a Windows environment
    runs-on: windows-latest

    # The steps for the job
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Compile the C file into pbw.exe
      - name: Compile C file
        run: gcc pbw.c -o pbw.exe

      # Step 3: Upload the compiled .exe to the GitHub Release
      - name: Upload to Release
        # This command uses the GitHub CLI (gh), which is pre-installed on the runner.
        # It uploads the specified file to the release that triggered this workflow.
        run: gh release upload "${{ github.event.release.tag_name }}" pbw.exe
        env:
          # The GITHUB_TOKEN is a special secret that gives the workflow permission
          # to upload files to your repository's releases. You don't need to set it up.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
