name: Build and Release pbw.exe

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build with MSBuild
        run: msbuild pbw.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pbw-exe
          path: Release/pbw.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: pbw-exe
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: pbw.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
